SET NOCOUNT ON

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DocumentViews')
BEGIN
	PRINT 'Creating DocumentViews table'
	CREATE TABLE [dbo].[DocumentViews] (
		Id BIGINT CONSTRAINT PK_DocumentViews_Id PRIMARY KEY IDENTITY(1,1) NOT NULL,
		DocumentId BIGINT CONSTRAINT FK_DocumentViews_DocumentId Foreign Key (DocumentId) REFERENCES Documents(Id) NOT NULL,
		UserId BIGINT CONSTRAINT FK_DocumentViews_UserId FOREIGN KEY (UserId) REFERENCES Users(Id) NOT NULL,
		ViewedAt DATETIME NOT NULL
	)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Followers')
BEGIN
	PRINT 'Creating Followers table'
	CREATE TABLE [dbo].[Followers] (
		Id BIGINT CONSTRAINT PK_Followers_Id PRIMARY KEY IDENTITY(1,1) NOT NULL,
		UserId BIGINT CONSTRAINT FK_Followers_UserId FOREIGN KEY (UserId) REFERENCES Users(Id) NOT NULL,
		FollowerId BIGINT CONSTRAINT FK_Followers_FollowerId Foreign Key (FollowerId) REFERENCES Users(Id) NOT NULL,
		FollowedAt DATETIME NOT NULL
	)
END
GO

SET NOCOUNT OFF