SET NOCOUNT ON

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Comments')
BEGIN
	PRINT 'Creating Comments table'
	CREATE TABLE [dbo].[Comments] (
		Id BIGINT CONSTRAINT PK_Comments_Id PRIMARY KEY IDENTITY(1,1) NOT NULL,
		DocumentId BIGINT NOT NULL,
		Text NVARCHAR(1000) NOT NULL,
		CreatedBy BIGINT NOT NULL,
		CreatedAt DATETIME NOT NULL,
		DeletedAt DATETIME NULL,
		CONSTRAINT FK_Comments_DocumentId FOREIGN KEY(DocumentId) REFERENCES Documents(Id),
		CONSTRAINT FK_Comments_CreatedBy FOREIGN KEY(CreatedBy) REFERENCES Users(Id)
	)
END
GO
        
SET NOCOUNT OFF


