IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Documents' AND COLUMN_NAME = 'Description' AND DATA_TYPE != 'NVARCHAR')
BEGIN
    PRINT 'Making Documents.Description unicode'
    ALTER TABLE Documents ALTER COLUMN Description NVARCHAR(4000) NULL
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Documents' AND COLUMN_NAME = 'Degree' AND DATA_TYPE != 'NVARCHAR')
BEGIN
    PRINT 'Making Documents.Degree unicode'
    ALTER TABLE Documents ALTER COLUMN Degree NVARCHAR(100) NOT NULL
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Documents' AND COLUMN_NAME = 'CourseName' AND DATA_TYPE != 'NVARCHAR')
BEGIN
    PRINT 'Making Documents.CourseName unicode'
    ALTER TABLE Documents ALTER COLUMN CourseName NVARCHAR(100) NULL
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Documents' AND COLUMN_NAME = 'CourseCode' AND DATA_TYPE != 'NVARCHAR')
BEGIN
    PRINT 'Making Documents.CourseCode unicode'
    ALTER TABLE Documents ALTER COLUMN CourseCode NVARCHAR(100) NULL
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Documents' AND COLUMN_NAME = 'Year' AND DATA_TYPE != 'NVARCHAR')
BEGIN
    PRINT 'Making Documents.Year unicode'
    ALTER TABLE Documents ALTER COLUMN Year NVARCHAR(20) NOT NULL
END
GO
        
SET NOCOUNT OFF


